name: AI Repo Agent

on:
  schedule:
    # Runs every Sunday at 00:00 UTC
    # Adjust cron expression as needed: https://crontab.guru/
    - cron: '0 0 * * SUN'
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab

jobs:
  run_agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Or specify a version like '3.9'

      - name: Install dependencies
        run: |
          pip install PyGithub requests

      - name: Run AI Agent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
          # For Gemini API Key, you'd need to add it as a repository secret
          # GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # The Python script handles the empty API key for Canvas, so no need to pass it here.
        run: |
          python ai_repo_agent.py
